baseURL = "https://dspg-young-scholars-program.github.io/dspg20halifax/"
languageCode = "en-us"
title = "UVA Biocomplexity Institute"
description = "Understanding Incarceration and Recidivism in Halifax County, Virginia"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "UVA Biocomplexity Institute"
    description = "Understanding Incarceration and Recidivism in Halifax County, Virginia"
    logo = "favicon/uva-dspg-logo.jpg"
    githubUsername = "uva-bi-sdad"
    accent = "#232D4B" # dark colors do best
    backgroundColor = "#FFFFFF"
    font = "Oxygen" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "ascetic" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Overview"
    weight = 1

[[menu.main]]
    url = "/methods/"
    name = "Data & Methods"
    weight = 3

[[menu.main]]
    url = "/findings/"
    name = "Findings"
    weight = 4
    
[[menu.main]]
    url = "/team/"
    name = "Team"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/DSPG-Young-Scholars-Program/dspg20fairfax/"
    name = "fab fa-github"
    weight = 2
    
[[menu.icon]]
    url = "mailto:kb7hp@virginia.edu"
    name = "far fa-envelope"
